In [2]:
import sys
sys.path.append(r'reflutils')
from reflutils import FileDialog
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [137]:
import pandas as pd

In [233]:
df = pd.DataFrame({
    "A": [1,1.5,.5, 4, 5, 6],
    "B": [4,4.5,3.5, 7, 8, 9],

})

df

     A    B
0  1.0  4.0
1  1.5  4.5
2  0.5  3.5
3  4.0  7.0
4  5.0  8.0
5  6.0  9.0

In [234]:
def addAverageCol(df, averagePoints: int):
    average = df.iloc[:averagePoints].mean(axis=0).to_frame().T
    average.index = [averagePoints-1]
    df_pre = df.iloc[:averagePoints]
    df_pre.index = [0]*averagePoints
    df_post = df.iloc[averagePoints:]
    new_df = pd.concat([df_pre, average, df_post])
    return new_df

In [235]:
addAverageCol(df, 3)

     A    B
0  1.0  4.0
0  1.5  4.5
0  0.5  3.5
2  1.0  4.0
3  4.0  7.0
4  5.0  8.0
5  6.0  9.0

In [227]:
df.iloc[3-1:6]

   A  B
2  3  6
3  4  7
4  5  8
5  6  9